# general configuration
url: "https://triticum01.github.io"       # My host url
baseurl: ''

# compass configuration
triticum:
  # an avatar or logo (optional)
  logo: "/images/red-shadow-sqr.png"
  # author will appear under the avatar (optional)
  author: "Triticum01"
  # tagline will appear under the title (optional)
  tagline: "Flowers blooming and petals failling according to the season, no need to intenvention."
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false
  # Twitter @username (as defined by the Twitter Card specs)
  twitter: "Triticum01"
  
  
# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
